on:
  workflow_dispatch:  # Allow manual triggers
  schedule:
    - cron: 0 2 * * *  # 4am UTC is 10pm in Beijing
name: Set nightly branch to master HEAD
jobs:
  master-to-nightly:
    if: github.repository == 'bytedance/fedlearner' # Don't do this in forks
    runs-on: ubuntu-latest
    steps:
    - uses: zofrex/mirror-branch@v1
      name: Set nightly branch to master HEAD
      with:
        target-branch: 'nightly'
