on:
  workflow_dispatch:  # Allow manual triggers
  schedule:
    - cron: 0 2 * * *  # 4am UTC is 10pm in Beijing
name: Set nightly branch to master HEAD
jobs:
  master-to-nightly:
    if: github.repository == 'bytedance/fedlearner' # Don't do this in forks
    runs-on: ubuntu-latest
    steps:
    - name: checkout 
      uses: actions/checkout@v1
      
    - uses: robotology/gh-action-nightly-merge@v1.3.1
      name: Set nightly branch to master HEAD
      with:
        stable_branch: 'master'
        development_branch: 'nightly'
        allow_ff: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
